export const AFFILIATE_REQUEST='AFFILIATE_REQUEST'
export const AFFILIATE_SUCCESS='AFFILIATE_SUCCESS'
export const AFFILIATE_FAIL='AFFILIATE_FAIL'

export const AFFILIATE_LINK_REQUEST='AFFILIATE_LINK_REQUEST'
export const AFFILIATE_LINK_SUCCESS='AFFILIATE_LINK_SUCCESS'
export const AFFILIATE_LINK_FAIL='AFFILIATE_LINK_FAIL'


export const AFFILIATE_PRODUCTS_REQUEST='AFFILIATE_PRODUCTS_REQUEST'
export const AFFILIATE_PRODUCTS_SUCCESS='AFFILIATE_PRODUCTS_SUCCESS'
export const AFFILIATE_PRODUCTS_FAIL='AFFILIATE_PRODUCTS_FAIL'
